services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
